name: build-image

on:
  push:
    branches:
      - master
      - staging
      - develop
    tags:
      - v*

# # permissions are needed if pushing to ghcr.io
permissions:
  packages: write
  contents: write

jobs:
  build:
    name: Packaging App
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
      - run: git pull
      - name: Setting-up NODE
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: |
          IMAGE_NAME=$(jq -r '.name' package.json)
          VERSION=$(jq -r '.version' package.json)
          echo $IMAGE_NAME $VERSION
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository }}/${{env.IMAGE_NAME}}
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Installing deps
        run: npm ci
      - name: Build Core FE
        run: npm run build
      - name: Login to GHCR registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Building Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
